# Generated by Django 4.2.5 on 2024-11-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=50)),
                ('domicilio_c', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono_c', models.CharField(blank=True, max_length=10, null=True)),
                ('e_mail_c', models.CharField(blank=True, max_length=50, null=True)),
                ('rfc_cliente', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComprasHecha',
            fields=[
                ('factura_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_c', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compras_hechas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVentasProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_v', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_ventas_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_almacen', models.IntegerField(blank=True, null=True)),
                ('precio_venta', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedore',
            fields=[
                ('id_prov', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_p', models.CharField(max_length=50)),
                ('domicilio_p', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono_p', models.CharField(blank=True, max_length=10, null=True)),
                ('e_mail_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('cred_deuda_a_favor', models.FloatField(blank=True, null=True)),
                ('horario_atencion', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajadore',
            fields=[
                ('id_t', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_t', models.CharField(max_length=50)),
                ('domicilio_t', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono_t', models.CharField(blank=True, max_length=10, null=True)),
                ('e_mail_t', models.CharField(blank=True, max_length=50, null=True)),
                ('horario', models.CharField(max_length=60)),
                ('imss', models.CharField(max_length=10)),
                ('rfc', models.CharField(blank=True, max_length=18, null=True)),
                ('sueldo_mensual', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trabajadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentasHecha',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('factura_venta', models.IntegerField(blank=True, null=True)),
                ('fecha_v', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ventas_hechas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleComprasProducto',
            fields=[
                ('factura_compra2', models.OneToOneField(db_column='factura_compra2', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='punto_venta.comprashecha')),
                ('cantidad_c', models.IntegerField(blank=True, null=True)),
                ('precio_unit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_compras_producto',
                'managed': False,
            },
        ),
    ]
